version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

  tcpserver:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      TCP_PORT: 9090
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: root
      DB_PASS: 123456
      BIND_ADDR: 0.0.0.0
    ports:
      - "9090:9090"

volumes:
  db_data:
